version: 1
default_environment: dev
project_id: 59dcf056-126a-4d76-8cd7-226d61c88a9a
environments:
- name: dev
- name: staging
- name: prod
plugins:
  extractors:
  - name: tap-theme-parks
    variant: danielpdwalker
    pip_url: git+https://github.com/DanielPDWalker/tap-theme-parks.git@v0.0.1
  loaders:
  - name: target-postgres
    variant: transferwise
    pip_url: pipelinewise-target-postgres
  - name: target-jsonl
    variant: andyh1203
    pip_url: target-jsonl
  transformers:
  - name: dbt
    variant: dbt-labs
    pip_url: "dbt-core~=1.3.0 dbt-postgres~=1.3.0 dbt-snowflake~=1.3.0\n"
  files:
  - name: files-dbt
    variant: matatika
    pip_url: git+https://github.com/Matatika/files-dbt@v1.0.x.1
jobs:
- name: tap-theme-parks-to-target-postgres
  tasks:
  - tap-theme-parks target-postgres
schedules:
- name: theme-park-sync
  interval: '@daily'
  job: tap-theme-parks-to-target-postgres
